### PR TITLE
Rename

### LINKED ISSUE #1026: "rename" project function does not work properly
Renaming a project should not change project paths. I didn't notice this behavior when it was created. For example, I have this project:
```
Project: dev **Current Project**
	Conf Path: /Users/emthompson/gmprocess_projects/dev/conf
	Data Path: /Users/emthompson/gmprocess_projects/dev/data
```
And renaming with
```
$ gmrecords proj --rename dev dev2
INFO 2022-10-09 10:12:32 | gmrecords._initialize: Logging level includes INFO.
INFO 2022-10-09 10:12:32 | gmrecords._initialize: PROJECTS_PATH: /Users/emthompson/.gmprocess
INFO 2022-10-09 10:12:32 | projects.main: Running subcommand 'projects'

Renamed 'dev' to 'dev2'.
```
Gives
```
Project: dev2 **Current Project**
	Conf Path: /Users/emthompson/gmprocess_projects/dev2/conf
	Data Path: /Users/emthompson/gmprocess_projects/dev2/data
```

### PR DESCRIPTION
**Pull request by emthompson-usgs**
Closes #1026.

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
I don't understand the desire to NOT rename the directory when renaming a project. The default conf and data paths for system level projects is `gmprojects/PROJECT_NAME/conf` and `gmprojects/PROJECT_NAME/data`. When renaming a project, I think most users would expect the data and conf directory paths to be updated to match the new name. This was the behavior before I updated the projects subcommand.

Can you explain the rationale for not renaming the project directory paths for conf and data?

**Comment by emthompson-usgs** [comment]
The simple reason is that the way things are currently configured, the path to the conf and data directories can be set to anything and the project name may or may not be a part of those paths. The reason we put in this flexibility is that it is likely convenient for some users to have multiple projects that have separate data directories but share a conf directory.

**Comment by baagaard-usgs** [comment]
Yes. But the conf and data directories are only renamed if the project name is in their filesystem path.

**Comment by baagaard-usgs** [comment]
Okay. We just need to make sure this behavior is well documented and mention this change in behavior in the Changelog.

**Pull request merged**
