### PR TITLE
Linear detrend and highpass corner adjustments.

### PR DESCRIPTION
**Pull request by jrekoske-usgs**
This PR changes the production config file to perform a linear detrend before removing instrument response. This may help with some issues we have noticed with long-period trends in the noise window.

This also requires that the highpass corner frequency is no less than 1 over the waveform duration.

### CODE REVIEW

**Comment by emthompson-usgs** [comment]
@arkottke @baagaard-usgs John showed found some events where there's a linear drift in one or more channels. Doing the linear detrend before the instrument really helps. Previously, we've just been doing the demean before instrument response correction, which I think is consistent with PEER processing. Can you think of a reason why we should stick to demean rather than detrend?

**Comment by baagaard-usgs** [comment]
Is a window used for the detrending or the whole record? In cases with strong motion and static offsets in acceleration, even demeaning causes problems unless the mean is only computed for the portion of the record before the static offsets. I think the same thing applies for linear detrending.

Does our test suite have any large amplitude motions from Northridge, Chi-Chi, Kobe, etc?

**Comment by arkottke** [comment]
Brad,

Do you have an example of this? We might want to reach out to the Prism
folks and see what they say on this matter.

- Albert

**Comment by emthompson-usgs** [comment]
@arkottke We had a meeting today and decided to build up a test suite of records that include some with baseline shifts and ones with the linear drifts. We'll then be able to look at the results for the current method and any possible changes to deal with the baseline shift prior to instrument response removal. For the California events you are processing now, I think that adding the linear detrend before the instrument removal would be an improvement.

**Comment by arkottke** [comment]
That sounds like a good approach going forward. I will make that change.

- Albert

**Pull request merged**
