### PR TITLE
Improve subcommand logging messages; refactor projects subcommand

### PR DESCRIPTION
**Pull request by baagaard-usgs**
* Improve subcommand logging messages to report progress in processing events.
* Make subcommands compatible with scripting (don't use sys.exit() except for fatal errors; use logging.error and exceptions).
* Refactor projects subcommand (clean up and make compatible with scripting).
* Update documentation for projects subcommand, including CLI and scripting tutorials.

### CODE REVIEW

**Review by emthompson-usgs — APPROVED** [review]
Thanks Brad. I've cloned this and tested it locally, trying to break the config in various ways and it seems to work well in all the edge cases I could come up with. I did notice that `Projects.__repr__` is now returning the relative paths and it used to be the absolute paths. It doesn't look like you changed this, so it must have been a mistake I made in my recent edits. So I'll send in a fix to that once this is merged.

**Comment by baagaard-usgs** [comment]
@emthompson-usgs For projects configuration in the local directory, I think relative paths makes sense. For system-level projects configuration, absolute paths make sense. Isn't this what you see?

I did keep code that compute the relative paths for non-Windows platforms.

**Comment by emthompson-usgs** [comment]
This is what I got for a system-level project:
```
$ gmrecords proj -c
No project config file detected. Please select a project setup option:
(1) Initialize the current directory as a gmrecords project,
    which will contain data and conf subdirectories.
(2) Setup a project with data and conf locations that are
    independent of the current directory.
(3) Exit.
> 2
Please enter a project title: [default] test
Please enter the conf: [/Users/emthompson/gmprocess_projects/test/conf]
Please enter the data: [/Users/emthompson/gmprocess_projects/test/data]
Please enter your name and email. This information will be added
to the config file and reported in the provenance of the data
processed in this project.
	Name: Eric
	Email address: eric@email.com

Created Project: test **Current Project**
	Conf Path: ../gmprocess_projects/test/conf
	Data Path: ../gmprocess_projects/test/data
INFO 2022-10-07 14:41:06 | gmrecords._initialize: Logging level includes INFO.
INFO 2022-10-07 14:41:06 | gmrecords._initialize: PROJECTS_PATH: /Users/emthompson/.gmprocess
INFO 2022-10-07 14:41:06 | projects.main: Running subcommand 'projects'
Please enter a project title: [default]
```
Note that it also prompts me to create a second project, which I think is undesirable. I didn't see this in my initial testing.

**Comment by emthompson-usgs** [comment]
Further testing, it seems that the only time I see the re-prompt for another project is creating a system level project and no projects.conf file previously existed.

**Comment by baagaard-usgs** [comment]
I found the problem. This doesn't happen unless you use the `proj` alias. I will add the fix to my comments in #1025

**Comment by emthompson-usgs** [comment]
Dang. I hadn't encountered issues that are specific to using aliases before so that wasn't on my radar.

**Pull request merged**
