### PR TITLE
Parallelization

### PR DESCRIPTION
**Pull request by emthompson-usgs**
- General improvements to iterations over waveforms. 
- Improved how we're using dask (still using `dask.distributed.Client`).
- The following subcommands now seem to be parallelized in a functional way:
    - `assemble` 
    - `process_waveforms`
    - `compute_waveform_metrics`
- The challenge is that read/write to ASDF files cannot occur in parallel. 
- I removed parallelization on `compute_station_metrics`. There's nothing that would obviously benefit from parallelization, and this is one of the faster subcommands anyway.

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
Theoretically, we should be able to access the ASDF (HDF5) file in parallel. It may require building HDF5 with parallel I/O enabled (and using MPI). The main question is how dask runs in parallel and what that means for read/write access to ASDF/HDF5.

**Comment by arkottke** [comment]
I looked at the HDF5 parallel access and it looks difficult -- especially because of the specific libraries. I also don't know if it is needed.

**Comment by emthompson-usgs** [comment]
For now, I'm just separating out the IO from the rest of the process, which was all grouped together before. I think that given the change in that we are not loading the full list of streams into memory prior to submitting the dask futures and are now more cleanly parallelizing on streams rather than events, this should be a significant step forward. We can do some profiling in the future to see if IO is taking up an unreasonable amount of time. But given the large dependency list that we have, it is pretty challenging to get the environment to build already, and I suspect it would get even worse if we try to include HDF5 with parallel IO.

**Comment by arkottke** [comment]
That makes a lot of sense at the moment. Do you want me to close the other issue?

**Comment by emthompson-usgs** [comment]
@arkottke Yes, if you are satisfied with the current progress for now. We can always re-open them as needed, but I've recently been trying to chip away at the large backlog of issues and get it down to a reasonable number.

**Pull request merged**
