### PR TITLE
Add waveqlab3d reader and corresponding test data.

### LINKED ISSUE #528: Add waveqlab3d reader for surface waveforms
Add reader for surface waveform output from `waveqlab3d` ground-motion simulation software.

## Metadata

Use YAML file for metadata. The raw `waveqlab3d` data files do not contain any metadata.

* **crs** Coordinate system as Proj parameters, WTK, or EPSG code
* **origin_x** X coordinate of grid origin in CRS coordinate system
* **origin_y** Y coordinate of grid origin in CRS coordinate system
* **endian_type** Endian type of floating point values in raw data files
* **filenames** Template for forming filenames of raw data files `{component}=x,y`
* **num_x** Number of grid points in the x coordinate direction
* **num_y** Number of grid points in the y coordinate direction
* **horizontal_resolution** Horizontal grid spacing in meters.
* **num_timesteps** Number of time steps in raw data files.
* **time_step** Time step in raw data files.
* **start_time** UTC data time of first time step.

## Raw data

* Velocity in m/s.
* 64-bit floating point values. 
* Each component in a different file.

### PR DESCRIPTION
**Pull request by baagaard-usgs**
Initial implementation and testing of `waveqlab3d` reader.

Still need to verify (1) ordering of values in fake data files matches simulation output and (2) geometry and topology information matches desired ordering.

Closes #528

### CODE REVIEW

**Comment by baagaard-usgs** [comment]
Please don't approve this yet. I need to make a small change to the test.

**Comment by baagaard-usgs** [comment]
Eric's comments:

1. If I clone your development branch and reinstall the environment, I only get 1 error (not the large number seen on the CI systems). But it is a yaml parsing error. 

2.The error that is causing this problem is in io/waveqlab3d/core.py, line 70 (the "except" part of your try block). The problem, I think, is that you are only catching for a specific error ("UnicodeDecodeError").  Buy on my system, the exception raised when trying to load the yaml file, when the input is not a yaml file is a "ScannerError". Thus, the error is not trapped, and the code halts. If I simply change that to a bare exception (by style, I know) the tests pass. 

You could try to make this one change and see if that resolves all of your issues. But I'm worried that you're branch does not have all of the commits we've made to master since the surface_waveforms branch was split off, and this might also be causing some problems. If so, we should figure out how to merge in those changes to the surface_waveforms development branch, and then into your waveqlab3d-reader feature branch.

**Comment by baagaard-usgs** [comment]
I will update the surface_waveforms branch to be in sync with master and fix the exception catching.

@emthompson-usgs Do you have a preference if the update from master is a fast-forward merge or rebase? Rebase is cleaner in the long-run, but requires people delete and checkout the branch again.

**Comment by emthompson-usgs** [comment]
Thanks for putting this here, much better than leaving this in email. I have always rebased but I don't really understand the difference and so I don't have a preference. Do whatever makes sense to you.

**Comment by baagaard-usgs** [comment]
I merged master updates into the surface_waveforms branch in the main repo (via rebase) and rebased this feature branch. I also fixed the try block in the waveqlab3d reader.

I think this is ready to be merged.

**Pull request merged**
